CREATE TABLE IF NOT EXISTS gruppa
(
НазваниеGruppi VARCHAR NOT NULL,
Примечание VARCHAR ,
PRIMARY KEY (НазваниеGruppi)
);
CREATE TABLE IF NOT EXISTS Client (
Fio VARCHAR NOT NULL,
NomerAbonimenta INT NOT NULL GENERATED ALWAYS AS IDENTITY,
DataRoshdenia DATE,
Pol VARCHAR,
Ves INT check(Ves>0),
Rost INT check(Rost>0),
NashaloAbonimenta DATE,
Okonshanie DATE NOT NULL,
Telephone VARCHAR NOT NULL,
НазваниеGruppi VARCHAR NOT NULL,
PRIMARY KEY (NomerAbonimenta),
FOREIGN KEY (НазваниеGruppi) REFERENCES gruppa(НазваниеGruppi)
);
CREATE TABLE IF NOT EXISTS Trener
(
Dolshnost VARCHAR NOT NULL,
IdentificatorTrener INT NOT NULL GENERATED ALWAYS AS IDENTITY,
Fio VARCHAR NOT NULL,
telephone VARCHAR NOT NULL,
PRIMARY KEY (IdentificatorTrener)
);
CREATE TABLE IF NOT EXISTS Raspisanie (
IdentificatorRaspisania int NOT NULL GENERATED By default AS IDENTITY,
VidZanatii VARCHAR NOT NULL,
Zal VARCHAR,
DenNedeli VARCHAR NOT NULL CHECK (DenNedeli IN ('пн', 'вт', 'ср', 'чт', 'пт', 'сб', 'вс')),
NachaloZanatii DATE NOT NULL,
Prodolshitelnost INT NOT NULL,
НазваниеGruppi VARCHAR NOT NULL,
IdentificatorTrener INT NOT NULL,
PRIMARY KEY (IdentificatorRaspisania),
FOREIGN KEY (НазваниеGruppi) REFERENCES gruppa(НазваниеGruppi),
FOREIGN KEY (IdentificatorTrener) REFERENCES Trener(IdentificatorTrener)
);
